#!/usr/bin/env python3
"""
Generate the permission set from the metadata that actually exists.

Hand-maintaining this file meant every new object or class needed a matching
edit, and appending to it broke the deploy outright: the Metadata API requires
same-named elements to be contiguous, and
"Element objectPermissions is duplicated at this location" is what you get
when they are not. Deriving the file removes both failure modes.

    python3 tools/gen_permset.py
"""

import glob
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, 'mdapi')
OUT = os.path.join(SRC, 'permissionsets', 'AI_Change_Console_User.permissionset')

# Order is the PermissionSet XSD sequence. Getting it wrong is a parse error.
NS = 'http://soap.sforce.com/2006/04/metadata'

# Field types that cannot carry field-level security.
UNPERMISSIONABLE = {'MasterDetail', 'AutoNumber', 'Summary'}

FIELD_BLOCK = re.compile(r'<fields>(.*?)</fields>', re.S)


def tag(block, name):
    m = re.search(r'<%s>([^<]*)</%s>' % (name, name), block)
    return m.group(1) if m else None


def collect():
    objects, fields = [], []
    for path in sorted(glob.glob(SRC + '/objects/*.object')):
        api = os.path.basename(path)[:-len('.object')]
        if api.endswith('__mdt'):
            continue                      # custom metadata needs no object perms
        objects.append(api)
        body = io.open(path, encoding='utf-8').read()
        for block in FIELD_BLOCK.findall(body):
            name = tag(block, 'fullName')
            ftype = tag(block, 'type')
            required = (tag(block, 'required') or 'false') == 'true'
            if not name or ftype in UNPERMISSIONABLE or required:
                continue
            fields.append((api, name))

    classes = sorted(
        os.path.basename(p)[:-4] for p in glob.glob(SRC + '/classes/*.cls')
        if not os.path.basename(p).endswith('Test.cls'))
    return objects, fields, classes


def build(objects, fields, classes):
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<PermissionSet xmlns="%s">' % NS]

    for c in classes:
        out += ['    <classAccesses>',
                '        <apexClass>%s</apexClass>' % c,
                '        <enabled>true</enabled>',
                '    </classAccesses>']

    out += ['    <description>Full access to the AI POC objects, the knowledge '
            'graph and the console. Grants nothing on pod objects; those stay '
            'governed by the Network Service profile. Generated by '
            'tools/gen_permset.py.</description>']

    for obj, field in fields:
        out += ['    <fieldPermissions>',
                '        <editable>true</editable>',
                '        <field>%s.%s</field>' % (obj, field),
                '        <readable>true</readable>',
                '    </fieldPermissions>']

    out += ['    <hasActivationRequired>false</hasActivationRequired>',
            '    <label>AI Change Console User</label>']

    for obj in objects:
        out += ['    <objectPermissions>',
                '        <allowCreate>true</allowCreate>',
                '        <allowDelete>true</allowDelete>',
                '        <allowEdit>true</allowEdit>',
                '        <allowRead>true</allowRead>',
                '        <modifyAllRecords>false</modifyAllRecords>',
                '        <object>%s</object>' % obj,
                '        <viewAllRecords>true</viewAllRecords>',
                '    </objectPermissions>']

    out.append('</PermissionSet>')
    return '\n'.join(out) + '\n'


def main():
    objects, fields, classes = collect()
    io.open(OUT, 'w', encoding='utf-8').write(build(objects, fields, classes))
    print('    permission set: %d objects, %d fields, %d classes'
          % (len(objects), len(fields), len(classes)))


if __name__ == '__main__':
    main()
